FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:11-build as build

# Install node dependencies
COPY package*.json ./
RUN npm install --production && npm cache clean --force && rm -rf /tmp/*


FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:11-run as run
VOLUME /data

# Install dependencies
RUN install_packages openssl

WORKDIR /app
COPY --from=build ./node_modules ./node_modules
COPY . .

# Start the container
CMD ["npm", "start"]
